### ISSUE TITLE
Generated code contains enum cases with no names

### ISSUE THREAD

**Issue by jakehawken** [Nordstrom/bluffalo#1]
After running Bluffalo on the Foundation class UserDefaults, the the first case in the UserDefaultsMethod enum is `case ()`

All corresponding switch statements contain a `(.(), .()):` case.

Needless to say, the compiler is not a fan.

**Comment by mattremick** [comment]
Yeah, that is for the convenience init(). Because 'init' is a language keyword it doesn't show up. I'll take a look at this. Thanks Jake.

**Comment by mattremick** [comment]
Fixed with PR.
