### ISSUE TITLE
Uncompilable enums generated when class contains overloaded functions

### ISSUE THREAD

**Issue by jakehawken** [Nordstrom/bluffalo#2]
The [ClassName]Method enum generated by a class with overloaded methods contains redundant cases. Their associated types are different, but the compiler does not deem that acceptable to differentiate them as enum cases, I guess.

For example, when running bluffalo on UserDefaults, which has a different version of `setValueForKey` for Ints, Floats, Doubles, etc, it generates the following cases:

```
case set_value_forKey(Any?, String)
case set_value_forKey(Int, String)
case set_value_forKey(Float, String)
case set_value_forKey(Double, String)
case set_value_forKey(Bool, String)
```

This causes the compiler error:
> Duplicate definition of enum element.

**Comment by jakehawken** [comment]
I tried solving this by collapsing all of them into the one that has an associated type of (Any?, String) but `Any` doesn't implement the Comparable protocol, so the generated `==` function doesn't compile either.

**Comment by khappucino** [comment]
so you may find yourself hand editing the fakes

**Comment by jakehawken** [comment]
Yeah, I figured as much. But hey, if a fix can be found I'd be glad for this to inspire it. :)

**Comment by jakehawken** [comment]
Honestly, I'm not sure how to solve this particular problem, even with hand-editing. I've been giving it serious thought.

**Comment by PeqNP** [comment]
I'll try and take a look at this ASAP and provide my findings in the next few days.

**Comment by jakehawken** [comment]
Thanks!

**Comment by PeqNP** [comment]
That last comment is not correct. I referenced the wrong issue. Looking at this now though.

**Comment by PeqNP** [comment]
This appears to already be fixed. The fix was to add the respective parameter names to the `enum`. Here's a test I ran:

```
import Foundation

class Dog {

    internal func bark(_ volume: Int, _ tenacity: Int) {
    }

    internal func playWith(tail: String) {
    }

    internal func playWith(toy: String, name: String) {
    }
}
```

Resulting `enum`:
```
public enum DogMethod: Equatable, Hashable {
    case bark_volume_tenacity(Int, Int)
    case playWith_tail(String)
    case playWith_toy_name(String, String)
    public var hashValue: Int {
        get {
            switch self {
            case .bark_volume_tenacity:
                return 0
            case .playWith_tail:
                return 1
            case .playWith_toy_name:
                return 2
            }
        }
    }
}
```

**Comment by PeqNP** [comment]
I'm not able to close the issue as I don't have access. When you get a chance may you please check on your end and close if fixed?
